{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay.player",
    "module": "clplayer-ijk",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "clplayer-ijk-1.0.aar",
          "url": "clplayer-ijk-1.0.aar",
          "size": 14747219,
          "sha512": "db936cf9b8835866f3cc183528784366ba2084e2999b61e2549f16cbdc5e62b2f90f4dc920c19b0c509b700da7983e830ab3e2dd3df2e98f0f5d8600a6a86677",
          "sha256": "6257010c83f817b7733a0748b06e45632f161fb8b16a6b75909f04a27508f108",
          "sha1": "e7635afa3cfa90afe97ec82a0c6b81a72c6d9696",
          "md5": "2724e08b66603158344e495eb120475e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "clplayer-ijk-1.0.aar",
          "url": "clplayer-ijk-1.0.aar",
          "size": 14747219,
          "sha512": "db936cf9b8835866f3cc183528784366ba2084e2999b61e2549f16cbdc5e62b2f90f4dc920c19b0c509b700da7983e830ab3e2dd3df2e98f0f5d8600a6a86677",
          "sha256": "6257010c83f817b7733a0748b06e45632f161fb8b16a6b75909f04a27508f108",
          "sha1": "e7635afa3cfa90afe97ec82a0c6b81a72c6d9696",
          "md5": "2724e08b66603158344e495eb120475e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "clplayer-ijk-1.0-sources.jar",
          "url": "clplayer-ijk-1.0-sources.jar",
          "size": 86131,
          "sha512": "384fdf0f9200989b98b193abec0c0403f0858cf4e09e5d4cb223c6f73cfc14aee9c81e39889f90a24aa2fee57301a96725d7be870cf2e46043124bba728ad472",
          "sha256": "79e7ea4be1b4fae618bb03482f7966e7e96b1945686740662d7b7229d6a39fbd",
          "sha1": "3be95a131f35e2b95fce8060c76e181db132c812",
          "md5": "d5f9a8cf88867f0d13ca6f682e215de4"
        }
      ]
    }
  ]
}
