{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.4.1.aar",
          "url": "seattle_tv_sdk-1.3.4.1.aar",
          "size": 141640,
          "sha512": "3a9c29d9904835b724bf53ae566c1da9ea295c06be4cb47b8234ebb62ab0fe308ef5b82eb8e41f0bf9cd113d93fe504e111283026da83dfdd9830c7102554d74",
          "sha256": "a905d902ecf5278f05871880d7c6c0bd22e55349881e42a2fe5fe28c64bae28a",
          "sha1": "0da7b8956373cf8fcf8e2c206ea3583c4d629dc0",
          "md5": "0cfcb2a3042cf6b8dbbd791069dd4344"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.4.1.aar",
          "url": "seattle_tv_sdk-1.3.4.1.aar",
          "size": 141640,
          "sha512": "3a9c29d9904835b724bf53ae566c1da9ea295c06be4cb47b8234ebb62ab0fe308ef5b82eb8e41f0bf9cd113d93fe504e111283026da83dfdd9830c7102554d74",
          "sha256": "a905d902ecf5278f05871880d7c6c0bd22e55349881e42a2fe5fe28c64bae28a",
          "sha1": "0da7b8956373cf8fcf8e2c206ea3583c4d629dc0",
          "md5": "0cfcb2a3042cf6b8dbbd791069dd4344"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.4.1-sources.jar",
          "url": "seattle_tv_sdk-1.3.4.1-sources.jar",
          "size": 70387,
          "sha512": "d40b5eaba32af4dbec36444f99ab37cb5262f288b92069cdcdfbf01c28aaedb4177c524d8964c89f6fabc265659b334c6a17a53f3cedd314acb1a4e523e197d9",
          "sha256": "920684631a95bfa31c0569b825fd9ec67514be4e477d76d3591623c14039df0f",
          "sha1": "cb5babff6420783b9f1f80e496e43e0b780687b0",
          "md5": "91b76b1648159f118e30078a0c424ab2"
        }
      ]
    }
  ]
}
