{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.6.aar",
          "url": "seattle_tv_sdk-1.3.2.6.aar",
          "size": 136269,
          "sha512": "00104771f1d0e6cda35aaa843ee23180e38d4e19495cd8b083de8c67b9b240e824aa901c74cd8234b426945c8c7a285112d101d072446953474705e468e06f0e",
          "sha256": "56dc1d7244110ebc87ebf744652325dddf0f10cd0ff661ce6156fc022aaffaae",
          "sha1": "c8cf376ec3b2fbd7ca9a655e1e09f06f37b2a43d",
          "md5": "226871f5a5b08240c9c34abecd97fd37"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.6.aar",
          "url": "seattle_tv_sdk-1.3.2.6.aar",
          "size": 136269,
          "sha512": "00104771f1d0e6cda35aaa843ee23180e38d4e19495cd8b083de8c67b9b240e824aa901c74cd8234b426945c8c7a285112d101d072446953474705e468e06f0e",
          "sha256": "56dc1d7244110ebc87ebf744652325dddf0f10cd0ff661ce6156fc022aaffaae",
          "sha1": "c8cf376ec3b2fbd7ca9a655e1e09f06f37b2a43d",
          "md5": "226871f5a5b08240c9c34abecd97fd37"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.6-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.6-sources.jar",
          "size": 65151,
          "sha512": "5547a514f62568c240acafd372111f1c32ee7a8c84c03f77f7b3051949b90fee6af0065b4c898acc63b8723e23651c9bff92e71995752784b3a912774f7651c0",
          "sha256": "368cc482e4ac30b43fab1339e1c5e407938729b42a092c31603b62ef4eeafd1c",
          "sha1": "6611adf47b41b6051d3644b12158897b1ee8db18",
          "md5": "8039901c3473acd9df0f5df33ebdad76"
        }
      ]
    }
  ]
}
