{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.3.aar",
          "url": "seattle_tv_sdk-1.3.2.3.aar",
          "size": 146554,
          "sha512": "c5edd3e7b4bba52de2c429b8996f724975dd6f38c00a9bcba76a52bdfa88ccb8ff76a0ebf0c71e66accf1694347326367455b68de4aaf8eb4399ee371f7a0d3e",
          "sha256": "9d33fbb9f1d9fdb722f6259f05810420cefa07a6aec8635b99fec6a0cfb4552c",
          "sha1": "1c45a52a4e90379c834e2ecaa367603542859d74",
          "md5": "1349b1746381d2b151980f3036ef5c64"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.3.aar",
          "url": "seattle_tv_sdk-1.3.2.3.aar",
          "size": 146554,
          "sha512": "c5edd3e7b4bba52de2c429b8996f724975dd6f38c00a9bcba76a52bdfa88ccb8ff76a0ebf0c71e66accf1694347326367455b68de4aaf8eb4399ee371f7a0d3e",
          "sha256": "9d33fbb9f1d9fdb722f6259f05810420cefa07a6aec8635b99fec6a0cfb4552c",
          "sha1": "1c45a52a4e90379c834e2ecaa367603542859d74",
          "md5": "1349b1746381d2b151980f3036ef5c64"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.3-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.3-sources.jar",
          "size": 75123,
          "sha512": "2573402fc20c4e0b2f3d9c5c022700f70ce3477b55011cdd667168293eaa6db8d3ee8e67bafcfbd04046452f3e4a865944b4dc2b9c8821c2d62333049df2e057",
          "sha256": "363cc7384a0050d6f8cdd7c3101481407db878592598d8c028ee67783ee9090d",
          "sha1": "05d0b869cae5fcfee85d224087ce0d67f1daee9b",
          "md5": "82125712b53f7497bd2bbd44cedc6221"
        }
      ]
    }
  ]
}
