{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.3.aar",
          "url": "seattle_tv_sdk-1.3.2.3.aar",
          "size": 146559,
          "sha512": "fc8a6569591db085522dd29c06543167ccd2e2d3d5664c59c9b1f53e771954b25e7c35cd24c61a31dd94b35f951dac452f5d52e60195e0f8bebf96acfa9e449e",
          "sha256": "34bfa5291ceec317bc08e0371399ba0e7827de73e7e51a681e35625a475783d0",
          "sha1": "1e03ab809c3a35e68ad268f5ec1ff2d3aa67309f",
          "md5": "28f257e16a8a08c3c11b4f82d8c7f477"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.3.aar",
          "url": "seattle_tv_sdk-1.3.2.3.aar",
          "size": 146559,
          "sha512": "fc8a6569591db085522dd29c06543167ccd2e2d3d5664c59c9b1f53e771954b25e7c35cd24c61a31dd94b35f951dac452f5d52e60195e0f8bebf96acfa9e449e",
          "sha256": "34bfa5291ceec317bc08e0371399ba0e7827de73e7e51a681e35625a475783d0",
          "sha1": "1e03ab809c3a35e68ad268f5ec1ff2d3aa67309f",
          "md5": "28f257e16a8a08c3c11b4f82d8c7f477"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.3-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.3-sources.jar",
          "size": 75103,
          "sha512": "758d5559fa27bbbf026933e6266fa819a677346a683da05b10fea1b5ffcffd7a3caf62a651c2644afaa57363209fb63c64d5a531065c177640b3f2ae1a0caa06",
          "sha256": "190db72dc71fdc170d98e817d85fbe4c08e15f298815d58600e62c634e2b8131",
          "sha1": "48406b56f7c2648da07b887b8a96dfe3ecc1bd1a",
          "md5": "216119b826b4f5fd1903a95086ef6e26"
        }
      ]
    }
  ]
}
