{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudinfinitegroup",
    "module": "seattle_tv_sdk",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.1.aar",
          "url": "seattle_tv_sdk-1.1.aar",
          "size": 98159,
          "sha512": "6780b93b857402a121f9d169cffc5c498df2d3de87ad22061ebc9cfb99dee238ed3ba5bc9c9a193c9eac6a76e77ecb3d2c8ffef9ff2b1c01995180e1c4a24bba",
          "sha256": "ba01e768118a3f51ba4ba314987b698b3a0920bdd37ba585d584de449e9286de",
          "sha1": "6f0e78d0d522d5a13330fc8b539c4f95702bfd17",
          "md5": "3109561cc2d4610ffc2b14fa8bfca2fd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.1.aar",
          "url": "seattle_tv_sdk-1.1.aar",
          "size": 98159,
          "sha512": "6780b93b857402a121f9d169cffc5c498df2d3de87ad22061ebc9cfb99dee238ed3ba5bc9c9a193c9eac6a76e77ecb3d2c8ffef9ff2b1c01995180e1c4a24bba",
          "sha256": "ba01e768118a3f51ba4ba314987b698b3a0920bdd37ba585d584de449e9286de",
          "sha1": "6f0e78d0d522d5a13330fc8b539c4f95702bfd17",
          "md5": "3109561cc2d4610ffc2b14fa8bfca2fd"
        }
      ]
    }
  ]
}
