{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.4.aar",
          "url": "seattle_tv_sdk-1.3.2.4.aar",
          "size": 148141,
          "sha512": "1ae1298f8392e5f802184a3d89c46b927537c1d58e3140e9084141e2a6d22e46977ee43e9aec1f2f6c7db9d05312fdcc36f5a8cf3d16b8ea686d0dfad47f824f",
          "sha256": "1a3a7370b924e06ea21b9542f5bb8ae3d17a8baeba72b3c2e000c78624fce8e9",
          "sha1": "528a06ce4d83c2ecb6d6765e5534b9ca0e6f3f8f",
          "md5": "35603aa380ee731dd181cb9c331535bf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.4.aar",
          "url": "seattle_tv_sdk-1.3.2.4.aar",
          "size": 148141,
          "sha512": "1ae1298f8392e5f802184a3d89c46b927537c1d58e3140e9084141e2a6d22e46977ee43e9aec1f2f6c7db9d05312fdcc36f5a8cf3d16b8ea686d0dfad47f824f",
          "sha256": "1a3a7370b924e06ea21b9542f5bb8ae3d17a8baeba72b3c2e000c78624fce8e9",
          "sha1": "528a06ce4d83c2ecb6d6765e5534b9ca0e6f3f8f",
          "md5": "35603aa380ee731dd181cb9c331535bf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.4-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.4-sources.jar",
          "size": 75333,
          "sha512": "3503e0a106067fe2143931f266fc2a4ca5c44d944a7feabd32ba51a20be64316ec9785c786e8893d067bc176905591390f570f8c243be8ef5953c56c07439af4",
          "sha256": "038025784ae420859d13c1754476417da60364f1b3bf093548a8955e55b52553",
          "sha1": "ead1b52a2f2ce9221170f7ca95d28712fb39f10d",
          "md5": "5a6d22eee220a59f25fa64c7c868f84b"
        }
      ]
    }
  ]
}
