{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "player-ijk",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-java",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.1.aar",
          "url": "seattle_tv_sdk-1.3.2.1.aar",
          "size": 138393,
          "sha512": "ec5d22518ef2ebb726166a2f30f1cca7bbfc96b1ef7cf2b416788adb51ecd6df90b59b37e9b183133c7e2861a0409a86db81c854f4fd6e87f829f78ade6c8a8d",
          "sha256": "3527f96af6799232bcace511a7c40124a746cef199e3a9a9d3529051ca1a504a",
          "sha1": "bff72ceb9622787924494aeae9ec06c981f1c22e",
          "md5": "95ac874680bad6221d300e4254e10e43"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "player-ijk",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-java",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.1.aar",
          "url": "seattle_tv_sdk-1.3.2.1.aar",
          "size": 138393,
          "sha512": "ec5d22518ef2ebb726166a2f30f1cca7bbfc96b1ef7cf2b416788adb51ecd6df90b59b37e9b183133c7e2861a0409a86db81c854f4fd6e87f829f78ade6c8a8d",
          "sha256": "3527f96af6799232bcace511a7c40124a746cef199e3a9a9d3529051ca1a504a",
          "sha1": "bff72ceb9622787924494aeae9ec06c981f1c22e",
          "md5": "95ac874680bad6221d300e4254e10e43"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.1-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.1-sources.jar",
          "size": 67727,
          "sha512": "91a59815357dbef51803c0008f523394f6f9ca04df71e9fdc7f31f850fd62ba8f3ea2c8bafa21880b5a037c0453419499ee13f1804d0a5147d3b039cb317497d",
          "sha256": "9e4f89b1cb5e3eb8315a7823d5e587e37a6afad5a027f242e6270a393496568b",
          "sha1": "d1166f6ee4fa459b7156756ced4324fc43c6533a",
          "md5": "350d471bd13e02f1f0fe019aaef2f05f"
        }
      ]
    }
  ]
}
