{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk_airmobi",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi-1.0.aar",
          "url": "seattle_tv_sdk_airmobi-1.0.aar",
          "size": 7141,
          "sha512": "e10c1f55f187692f846fe40bee09302d91f3e4a35c83ba6c34fcbd79ff5c2fd399e743fd8e7f5a61bec6ae4aa79e56950b3e92a36b00cd0d1857e8cf4b26f809",
          "sha256": "046480e1eb357534ed94b3eb34954d9d994bdc7b7c60f9322c00bd2d80cb7a31",
          "sha1": "63a6da277b34c107e38418a3cacf922e636068d2",
          "md5": "ad45e561dab382b2fc36913ec4661e6a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "adsdk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi-1.0.aar",
          "url": "seattle_tv_sdk_airmobi-1.0.aar",
          "size": 7141,
          "sha512": "e10c1f55f187692f846fe40bee09302d91f3e4a35c83ba6c34fcbd79ff5c2fd399e743fd8e7f5a61bec6ae4aa79e56950b3e92a36b00cd0d1857e8cf4b26f809",
          "sha256": "046480e1eb357534ed94b3eb34954d9d994bdc7b7c60f9322c00bd2d80cb7a31",
          "sha1": "63a6da277b34c107e38418a3cacf922e636068d2",
          "md5": "ad45e561dab382b2fc36913ec4661e6a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi-1.0-sources.jar",
          "url": "seattle_tv_sdk_airmobi-1.0-sources.jar",
          "size": 5305,
          "sha512": "0f823eb539550c846e949a77cfb86e1ae892dc9973a37737ba3c89e0066e15c96ce0f7aedd4a5ad90088b78d8a085b1cd6a73cb65ee30a0db2c9eb56045877f3",
          "sha256": "8a3eadda541c2c69ea185af7edb9f1efcc889098d0d1e473fdc42adf06403107",
          "sha1": "6e495cb860dcdaeb505c362107037b266bdac923",
          "md5": "3b5cd37a4403e2d5dc44e8f3793bc96c"
        }
      ]
    }
  ]
}
