{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.github.goooler.mmkv",
          "module": "mmkv",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.5.aar",
          "url": "seattle_tv_sdk-1.3.5.aar",
          "size": 143956,
          "sha512": "52c860d245d64cd81a222e5abf8e92eece76dd7747b9c60eae2e29f09644686c7e3296c9a4796fc2869f178bb46868bf05926d58fce3a6508292c5442b034bd2",
          "sha256": "5771e1113275d615e05fe2a2c6b59e903509fe19086481ce50685d3590cca060",
          "sha1": "03f8709e6e5e55c0c3c0883b354c1b9e75078b5e",
          "md5": "3251eddc8fb037179c66b4dd02b452cd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.github.goooler.mmkv",
          "module": "mmkv",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.5.aar",
          "url": "seattle_tv_sdk-1.3.5.aar",
          "size": 143956,
          "sha512": "52c860d245d64cd81a222e5abf8e92eece76dd7747b9c60eae2e29f09644686c7e3296c9a4796fc2869f178bb46868bf05926d58fce3a6508292c5442b034bd2",
          "sha256": "5771e1113275d615e05fe2a2c6b59e903509fe19086481ce50685d3590cca060",
          "sha1": "03f8709e6e5e55c0c3c0883b354c1b9e75078b5e",
          "md5": "3251eddc8fb037179c66b4dd02b452cd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.5-sources.jar",
          "url": "seattle_tv_sdk-1.3.5-sources.jar",
          "size": 70845,
          "sha512": "0f0f6bb6791aa3914e95057c600c63ecc651fef30a56abd95000efe02a7172a709f3911d5f7bde079b3b6c9e1b2fac13fc3ec9c0b35a9fa48005ae30017ad82d",
          "sha256": "7be0f0248e8d49648c49d700ccdfc1e50701d1edc6b7070d4aaf38df6333a494",
          "sha1": "ab4310363f3f83db1f64108afc1199455baaed46",
          "md5": "a0ab518d67ee9ab844738dac07f2c714"
        }
      ]
    }
  ]
}
