{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2.aar",
          "url": "seattle_tv_sdk-1.3.2.7.2.aar",
          "size": 134998,
          "sha512": "3475e7bd0a0564df1c923c0b21d01564223b51f66adbbea458388ce4924523ae533dae0774c0b6fab11f24918dfe515581b465c160e9b35ffdbff80cf4c136a3",
          "sha256": "a29d48ce4447958cfabee9aab2346447e93fc8ebf870463752ed6906d185d230",
          "sha1": "7d0a64ea779151ed6d5982a03c7c8a74ab8de426",
          "md5": "c62be0a2ac726687507acdb822fc7cf6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2.aar",
          "url": "seattle_tv_sdk-1.3.2.7.2.aar",
          "size": 134998,
          "sha512": "3475e7bd0a0564df1c923c0b21d01564223b51f66adbbea458388ce4924523ae533dae0774c0b6fab11f24918dfe515581b465c160e9b35ffdbff80cf4c136a3",
          "sha256": "a29d48ce4447958cfabee9aab2346447e93fc8ebf870463752ed6906d185d230",
          "sha1": "7d0a64ea779151ed6d5982a03c7c8a74ab8de426",
          "md5": "c62be0a2ac726687507acdb822fc7cf6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7.2-sources.jar",
          "size": 65961,
          "sha512": "d9d365a9f1bafdf9d73369b7ec2d118b3ee636888715e2d7b48d3e414b73147fa9d36a33894849a2f3de9ab0fb7198aa9a1e7935485ab34f8235575cc1789f7a",
          "sha256": "77a87287f85e2d2ce0e166a5938f29fe2f96da1e21c0d83301ba8d5fa9ff0a87",
          "sha1": "2a979215ad376a2e2db5187d9ae779c5036d7c2d",
          "md5": "55bff4e73670b1d8d3045fb26bb43b48"
        }
      ]
    }
  ]
}
