{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2.aar",
          "url": "seattle_tv_sdk-1.3.2.7.2.aar",
          "size": 134804,
          "sha512": "edc92591ac358322ff576068d878016f1e76e63d25e5bb5faaea224fcbd32d196b6c4846cbe7e0098558f8694c2dc00595acb333edafc2e5e25a3945d18fe85d",
          "sha256": "670198d0d6940bf41fccb978d4df8a234108570b189189c9e38a871260463fbf",
          "sha1": "a46bc11b81d3c055ce51216519356f55b7151271",
          "md5": "7cc48a937996adc2119bc8543caf46b1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2.aar",
          "url": "seattle_tv_sdk-1.3.2.7.2.aar",
          "size": 134804,
          "sha512": "edc92591ac358322ff576068d878016f1e76e63d25e5bb5faaea224fcbd32d196b6c4846cbe7e0098558f8694c2dc00595acb333edafc2e5e25a3945d18fe85d",
          "sha256": "670198d0d6940bf41fccb978d4df8a234108570b189189c9e38a871260463fbf",
          "sha1": "a46bc11b81d3c055ce51216519356f55b7151271",
          "md5": "7cc48a937996adc2119bc8543caf46b1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7.2-sources.jar",
          "size": 65899,
          "sha512": "619a8e0278a5b77e00583f897cf40f6feba80b6a0c0aa261cce80d238f631f3a5c8c2ea162e45a65b5374c56e17530fb74ab90dfadba1809f88a46d11142a950",
          "sha256": "b35cbdbd58a9f021b4348040369412b6d14b4dd2a381b4385e3c3d281f846ac9",
          "sha1": "7322714dcc1942867e86be3b2e0a6f98b78d8649",
          "md5": "eefc49cce009a4b2e98cc60eefadca7d"
        }
      ]
    }
  ]
}
