{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2.aar",
          "url": "seattle_tv_sdk-1.3.2.7.2.aar",
          "size": 134706,
          "sha512": "47fe66b58e0941a99492913b351798576c936531ec48ca543485571442219381e5ce9a4a385322be1d466a7c9a87ac2b52ccf2f84dfc13be6128d4af675ba034",
          "sha256": "b1d096d7f795ab8696d9bfcab8fe71cce3bd797d4897e380df11295a544bf6b9",
          "sha1": "0434070c92af4ac8bab17b38559af25bd4fe467c",
          "md5": "1494badc96f790c3d82c047b8e45eaf2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2.aar",
          "url": "seattle_tv_sdk-1.3.2.7.2.aar",
          "size": 134706,
          "sha512": "47fe66b58e0941a99492913b351798576c936531ec48ca543485571442219381e5ce9a4a385322be1d466a7c9a87ac2b52ccf2f84dfc13be6128d4af675ba034",
          "sha256": "b1d096d7f795ab8696d9bfcab8fe71cce3bd797d4897e380df11295a544bf6b9",
          "sha1": "0434070c92af4ac8bab17b38559af25bd4fe467c",
          "md5": "1494badc96f790c3d82c047b8e45eaf2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.2-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7.2-sources.jar",
          "size": 65613,
          "sha512": "373c6a31c373042625ce77da405511c1320e5c39e1ca4d4fc92a883ac47f09fa3a52e49a9c3f0c36cd6a02e9d7a874c7db525ede35d07a75ef63884b2def664f",
          "sha256": "3940b645641bb7c600c4ffdaf756f4ad292fc052c91a0167a4cff3448a0d40ff",
          "sha1": "b5a76fb306146d514985c533b003f52af57d857c",
          "md5": "b6777fc69294eb16f78aa8f3eff239fb"
        }
      ]
    }
  ]
}
