{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.2.8.aar",
          "url": "seattle_tv_sdk-1.2.8.aar",
          "size": 150845,
          "sha512": "d6b82b4e4ecdf3f5aba01862a5ac89b3a7d989cb66272e8e47c0bc7d19fdae4b5a896a5bd44786a7d0c130b5c12efb03a159a7c93d28a552d9d3869c12fb7a1c",
          "sha256": "3da2ab606dc80933d3f55c69fd48f9c8ec632e293583744bb1288eb8d96a7faf",
          "sha1": "2ad24f8b080c8139a2862ae4ab7c860d9a0a90c4",
          "md5": "c802d0f94efe2bbaac0c6ccbbed2022d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.2.8.aar",
          "url": "seattle_tv_sdk-1.2.8.aar",
          "size": 150845,
          "sha512": "d6b82b4e4ecdf3f5aba01862a5ac89b3a7d989cb66272e8e47c0bc7d19fdae4b5a896a5bd44786a7d0c130b5c12efb03a159a7c93d28a552d9d3869c12fb7a1c",
          "sha256": "3da2ab606dc80933d3f55c69fd48f9c8ec632e293583744bb1288eb8d96a7faf",
          "sha1": "2ad24f8b080c8139a2862ae4ab7c860d9a0a90c4",
          "md5": "c802d0f94efe2bbaac0c6ccbbed2022d"
        }
      ]
    }
  ]
}
