{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk_airmobi_aike",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "adsdk_aike",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi_aike-1.0.1.aar",
          "url": "seattle_tv_sdk_airmobi_aike-1.0.1.aar",
          "size": 7238,
          "sha512": "0d1682599fb281f3e398f4287c2732d6288f2fa6c3680a772657c2e5ab08263568c8de2ae829f94e80a6d5991d9c52e71077dd513dd8a48aeef115b6e61a7c2a",
          "sha256": "a20bc6a6877c5339950c60118a4a314838549f3f7d040fa417def01a90fef77d",
          "sha1": "7c430f18b0e2876f13b256156301ebe9433c832e",
          "md5": "9dd25d1fe600de86a4a1449b627736c9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "adsdk_aike",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi_aike-1.0.1.aar",
          "url": "seattle_tv_sdk_airmobi_aike-1.0.1.aar",
          "size": 7238,
          "sha512": "0d1682599fb281f3e398f4287c2732d6288f2fa6c3680a772657c2e5ab08263568c8de2ae829f94e80a6d5991d9c52e71077dd513dd8a48aeef115b6e61a7c2a",
          "sha256": "a20bc6a6877c5339950c60118a4a314838549f3f7d040fa417def01a90fef77d",
          "sha1": "7c430f18b0e2876f13b256156301ebe9433c832e",
          "md5": "9dd25d1fe600de86a4a1449b627736c9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi_aike-1.0.1-sources.jar",
          "url": "seattle_tv_sdk_airmobi_aike-1.0.1-sources.jar",
          "size": 5305,
          "sha512": "0f823eb539550c846e949a77cfb86e1ae892dc9973a37737ba3c89e0066e15c96ce0f7aedd4a5ad90088b78d8a085b1cd6a73cb65ee30a0db2c9eb56045877f3",
          "sha256": "8a3eadda541c2c69ea185af7edb9f1efcc889098d0d1e473fdc42adf06403107",
          "sha1": "6e495cb860dcdaeb505c362107037b266bdac923",
          "md5": "3b5cd37a4403e2d5dc44e8f3793bc96c"
        }
      ]
    }
  ]
}
