{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.2.9.aar",
          "url": "seattle_tv_sdk-1.2.9.aar",
          "size": 151231,
          "sha512": "d8a002e097c2bcbb638b2ea138c90e2d2fbcd9295651c52bb5166e737ed31be688d2ce6b4c2fd6e8aae05caf263a318f1a5c38411de346924c2ca9c057f2c5d6",
          "sha256": "4b403d4afab34b4935378efdab22dd7b80b6544186fd133a04f5561ffe0c69e7",
          "sha1": "02d822c4ae0eb323e4fed3a765880ef5bbba1fc2",
          "md5": "58dc217a861606c05d76f9700ecd218a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.2.9.aar",
          "url": "seattle_tv_sdk-1.2.9.aar",
          "size": 151231,
          "sha512": "d8a002e097c2bcbb638b2ea138c90e2d2fbcd9295651c52bb5166e737ed31be688d2ce6b4c2fd6e8aae05caf263a318f1a5c38411de346924c2ca9c057f2c5d6",
          "sha256": "4b403d4afab34b4935378efdab22dd7b80b6544186fd133a04f5561ffe0c69e7",
          "sha1": "02d822c4ae0eb323e4fed3a765880ef5bbba1fc2",
          "md5": "58dc217a861606c05d76f9700ecd218a"
        }
      ]
    }
  ]
}
