{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-arm64",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.1.aar",
          "url": "seattle_tv_sdk-1.3.1.aar",
          "size": 132497,
          "sha512": "8ee5485d4f43da44cb04eba928c04348d4f83a95e0fddd2604b508ceab410ecbf9a95854223ee918bae4b50f22f1f18f092dba8544c2c71ec99c701c233879d7",
          "sha256": "18c2bbe09107ab7571a6b4ed9f35a3f359e47339db319a9b7183fd71ea16c60e",
          "sha1": "1fc7c3fb0f7b9bbfb4188bd9804cd769d07117f7",
          "md5": "fec981d1104cdad0a5d0a86a360c4d5f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-arm64",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.1.aar",
          "url": "seattle_tv_sdk-1.3.1.aar",
          "size": 132497,
          "sha512": "8ee5485d4f43da44cb04eba928c04348d4f83a95e0fddd2604b508ceab410ecbf9a95854223ee918bae4b50f22f1f18f092dba8544c2c71ec99c701c233879d7",
          "sha256": "18c2bbe09107ab7571a6b4ed9f35a3f359e47339db319a9b7183fd71ea16c60e",
          "sha1": "1fc7c3fb0f7b9bbfb4188bd9804cd769d07117f7",
          "md5": "fec981d1104cdad0a5d0a86a360c4d5f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.1-sources.jar",
          "url": "seattle_tv_sdk-1.3.1-sources.jar",
          "size": 66695,
          "sha512": "52dcd868ea2122c3c518a09a1c230ec13ae42dbe48e4aa5480c4d9e231aaaaba1126c2650f8d2c46943fece7c3fe0710396818bb8cccd23cf172ca72c86d8d30",
          "sha256": "4fc0838ca113882aa8a14f641ee94dde100aa75ceb99bc0a22bcd58bd34df125",
          "sha1": "2843802918ee5ed8c457a31fca5e30fdc7d6822a",
          "md5": "a5728bed24c914565cebf3e149f04b58"
        }
      ]
    }
  ]
}
