{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk_whaltv",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.zeasn",
          "module": "ad_vast_sdk",
          "version": {
            "requires": "8.0.5.16"
          }
        },
        {
          "group": "com.zeasn",
          "module": "tou_sdk",
          "version": {
            "requires": "4.0.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "leanback"
            }
          ]
        },
        {
          "group": "com.zeasn.ad.connector",
          "module": "connector",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "com.zeasn.common",
          "module": "common",
          "version": {
            "requires": "1.1.89"
          }
        },
        {
          "group": "com.zeasn.analytics",
          "module": "core",
          "version": {
            "requires": "1.1.89"
          }
        },
        {
          "group": "com.zeasn",
          "module": "dp-api",
          "version": {
            "requires": "0.2.25"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-ima",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-cronet",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-pal",
          "version": {
            "requires": "20.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "recyclerview",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_whaltv-1.0.1.aar",
          "url": "seattle_tv_sdk_whaltv-1.0.1.aar",
          "size": 13476,
          "sha512": "f9b5d2816900abc551e0db088cce4148d2e3e657dd86415da084ffa578f8978e7e2fc9e6fbb2d47a7b8a93f325f7c657605a4bfd77d89c14788bc5fb106e199a",
          "sha256": "0a7f55ba2e7fa08ee87384f4035c89bbd8990c952c3e135dbe8c6355c3c23be3",
          "sha1": "4f9229170d2224b3fff4fe3d32460da42fa8f49c",
          "md5": "6cb9ee2d216a18df3905c47726a995f8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.zeasn",
          "module": "ad_vast_sdk",
          "version": {
            "requires": "8.0.5.16"
          }
        },
        {
          "group": "com.zeasn",
          "module": "tou_sdk",
          "version": {
            "requires": "4.0.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "leanback"
            }
          ]
        },
        {
          "group": "com.zeasn.ad.connector",
          "module": "connector",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "com.zeasn.common",
          "module": "common",
          "version": {
            "requires": "1.1.89"
          }
        },
        {
          "group": "com.zeasn.analytics",
          "module": "core",
          "version": {
            "requires": "1.1.89"
          }
        },
        {
          "group": "com.zeasn",
          "module": "dp-api",
          "version": {
            "requires": "0.2.25"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-ima",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-cronet",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-pal",
          "version": {
            "requires": "20.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "recyclerview",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_whaltv-1.0.1.aar",
          "url": "seattle_tv_sdk_whaltv-1.0.1.aar",
          "size": 13476,
          "sha512": "f9b5d2816900abc551e0db088cce4148d2e3e657dd86415da084ffa578f8978e7e2fc9e6fbb2d47a7b8a93f325f7c657605a4bfd77d89c14788bc5fb106e199a",
          "sha256": "0a7f55ba2e7fa08ee87384f4035c89bbd8990c952c3e135dbe8c6355c3c23be3",
          "sha1": "4f9229170d2224b3fff4fe3d32460da42fa8f49c",
          "md5": "6cb9ee2d216a18df3905c47726a995f8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk_whaltv-1.0.1-sources.jar",
          "url": "seattle_tv_sdk_whaltv-1.0.1-sources.jar",
          "size": 7655,
          "sha512": "c0f6d119976702f85fb24a5e8dbf458280b3d0a211c6924951c990ec80b4616281b742353a0cf56a7b441f7e5b1d4fdae0226cfa533a01c802e80ec2aa582b9d",
          "sha256": "284fda6dfce83e7c02a3714e1c338b8220cb5616abe98af49a0b3c85025e3d75",
          "sha1": "e438c1e82ef38a2279f8e0b9f41109e4b3bcc409",
          "md5": "469ccab00d214b3727159b9ee679e367"
        }
      ]
    }
  ]
}
