{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk_airmobi_nie",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "cn.coolplay",
          "module": "adsdk_nie",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi_nie-1.0.aar",
          "url": "seattle_tv_sdk_airmobi_nie-1.0.aar",
          "size": 7140,
          "sha512": "a8cbd2b5087e80586196905ba548fccae037fa4137882e062c80433c4723e3f998041bb05ebcd396f090196e5e43049dd27e0ac6007ada0e233983f94038c43d",
          "sha256": "10777584edc9f455c5917674669cecf3e8eb740a1e9e2dc3aa6fb4342b740f4f",
          "sha1": "47f24121b31f25a0896131350db776bf3c19e673",
          "md5": "d4e159eac285dea889b4dcb8c169dd09"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        },
        {
          "group": "cn.coolplay",
          "module": "adsdk_nie",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi_nie-1.0.aar",
          "url": "seattle_tv_sdk_airmobi_nie-1.0.aar",
          "size": 7140,
          "sha512": "a8cbd2b5087e80586196905ba548fccae037fa4137882e062c80433c4723e3f998041bb05ebcd396f090196e5e43049dd27e0ac6007ada0e233983f94038c43d",
          "sha256": "10777584edc9f455c5917674669cecf3e8eb740a1e9e2dc3aa6fb4342b740f4f",
          "sha1": "47f24121b31f25a0896131350db776bf3c19e673",
          "md5": "d4e159eac285dea889b4dcb8c169dd09"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi_nie-1.0-sources.jar",
          "url": "seattle_tv_sdk_airmobi_nie-1.0-sources.jar",
          "size": 5305,
          "sha512": "0f823eb539550c846e949a77cfb86e1ae892dc9973a37737ba3c89e0066e15c96ce0f7aedd4a5ad90088b78d8a085b1cd6a73cb65ee30a0db2c9eb56045877f3",
          "sha256": "8a3eadda541c2c69ea185af7edb9f1efcc889098d0d1e473fdc42adf06403107",
          "sha1": "6e495cb860dcdaeb505c362107037b266bdac923",
          "md5": "3b5cd37a4403e2d5dc44e8f3793bc96c"
        }
      ]
    }
  ]
}
