{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "player-ijk",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-java",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.aar",
          "url": "seattle_tv_sdk-1.3.2.aar",
          "size": 137916,
          "sha512": "122671f3dbd3a1a1e058a7282ed2cfe3af47fcedf3e3c79d3be5f932cd45a525a49bf1330b1bf5bf372a0c86b8713027e7eae8b7862569218ec706d999056bd1",
          "sha256": "70327412025ef8be61b50d62471dc65dfb9c2599abaf77fbe49aa630b776d2ca",
          "sha1": "c4e047e1ae163c6e6287c8c622074601bf2ffbd0",
          "md5": "a7a01740c811f80908e1a7116e320bf0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "player-ijk",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "dkplayer-java",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.aar",
          "url": "seattle_tv_sdk-1.3.2.aar",
          "size": 137916,
          "sha512": "122671f3dbd3a1a1e058a7282ed2cfe3af47fcedf3e3c79d3be5f932cd45a525a49bf1330b1bf5bf372a0c86b8713027e7eae8b7862569218ec706d999056bd1",
          "sha256": "70327412025ef8be61b50d62471dc65dfb9c2599abaf77fbe49aa630b776d2ca",
          "sha1": "c4e047e1ae163c6e6287c8c622074601bf2ffbd0",
          "md5": "a7a01740c811f80908e1a7116e320bf0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2-sources.jar",
          "url": "seattle_tv_sdk-1.3.2-sources.jar",
          "size": 67601,
          "sha512": "9d3730acd0d3cb139f2b8605d57890abe1400f6e089fddc95bb8b6bd900f20a8a557927740f85246557f229f153bb421ce1030aa974e367c8f2b49a7bc4e3a7b",
          "sha256": "43355757b2252a347a89e421f2d94fc68ac19fafcc50f167a4a84d34231aabde",
          "sha1": "794925dd7c1937f7d3dc13a4b35a58b114904e90",
          "md5": "ee6deffd3fd3b4442d717a800c8b77d3"
        }
      ]
    }
  ]
}
