{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.2.3.aar",
          "url": "seattle_tv_sdk-1.2.3.aar",
          "size": 127834,
          "sha512": "f78b865d708f315c42fd664891ff314bc8c139e6c87dba72b912c44e0562ea02d40b20df473494fa82be7c483290b5c4ea534870f4291a60ad22839a8e0b5faa",
          "sha256": "029734083a2d11d8e4aabc895aa5f2c5ed18c1751daf4843bbd0c3a0fb86274b",
          "sha1": "ea6459bd545aba1a89bcb3a7995cad239a69b2eb",
          "md5": "9518b5770ee07cc140f3c594664b0d18"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.2.3.aar",
          "url": "seattle_tv_sdk-1.2.3.aar",
          "size": 127834,
          "sha512": "f78b865d708f315c42fd664891ff314bc8c139e6c87dba72b912c44e0562ea02d40b20df473494fa82be7c483290b5c4ea534870f4291a60ad22839a8e0b5faa",
          "sha256": "029734083a2d11d8e4aabc895aa5f2c5ed18c1751daf4843bbd0c3a0fb86274b",
          "sha1": "ea6459bd545aba1a89bcb3a7995cad239a69b2eb",
          "md5": "9518b5770ee07cc140f3c594664b0d18"
        }
      ]
    }
  ]
}
