{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.3.aar",
          "url": "seattle_tv_sdk-1.3.3.aar",
          "size": 139339,
          "sha512": "3418c0aed917cf4375d8bf8dadbfa0de4d79ea3ff939906469aed7d5a47b65abc17991fc0258a0b52cdd89ea16a389a5c42ab82b463639c8caf98ca097dbc7c0",
          "sha256": "9ebba3b952a68a5b0d255dbbe247be0adc38a0e75b22a840a34e9cf497488b7f",
          "sha1": "96721d7c2c327c36c0ffb99759bbdc2a65041431",
          "md5": "1e8922fe89b02a74667cf7b6127b1459"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.3.aar",
          "url": "seattle_tv_sdk-1.3.3.aar",
          "size": 139339,
          "sha512": "3418c0aed917cf4375d8bf8dadbfa0de4d79ea3ff939906469aed7d5a47b65abc17991fc0258a0b52cdd89ea16a389a5c42ab82b463639c8caf98ca097dbc7c0",
          "sha256": "9ebba3b952a68a5b0d255dbbe247be0adc38a0e75b22a840a34e9cf497488b7f",
          "sha1": "96721d7c2c327c36c0ffb99759bbdc2a65041431",
          "md5": "1e8922fe89b02a74667cf7b6127b1459"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.3-sources.jar",
          "url": "seattle_tv_sdk-1.3.3-sources.jar",
          "size": 68493,
          "sha512": "dddca6c99592f6a18d038e03f5836a2172ecf3d448403cee2d5bff2b0601b0c45b460144199c85f380b3d6127759cedb965a52b9c6ba982c6c26c2d40c0b9f52",
          "sha256": "066179a76a5ca7e174ec9a64c723c574394763530501d37d794763a87fb17d23",
          "sha1": "98843d64cf55f8240bf0ff654aee11d00ddc2fcd",
          "md5": "808d1561297d9e3cc92c50484e3c53b1"
        }
      ]
    }
  ]
}
