{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.3.aar",
          "url": "seattle_tv_sdk-1.3.2.7.3.aar",
          "size": 135174,
          "sha512": "7990af6be9ba51228fff07b5d4a9b3227d0709b0fec787d7cf939a92a19eb6e69182d6713ddd7666fad44c6e3fba1457a343fc9e060902db28b6d65c12b6c724",
          "sha256": "fdf757715a5a6174e6b806bef341316410ba8614b9dca34d940183ca3c014ddd",
          "sha1": "617f4c8f7d417e7f045249b8b02f3f78ca616872",
          "md5": "b5afa9848bcdfdce08252e8ccebd6ead"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.3.aar",
          "url": "seattle_tv_sdk-1.3.2.7.3.aar",
          "size": 135174,
          "sha512": "7990af6be9ba51228fff07b5d4a9b3227d0709b0fec787d7cf939a92a19eb6e69182d6713ddd7666fad44c6e3fba1457a343fc9e060902db28b6d65c12b6c724",
          "sha256": "fdf757715a5a6174e6b806bef341316410ba8614b9dca34d940183ca3c014ddd",
          "sha1": "617f4c8f7d417e7f045249b8b02f3f78ca616872",
          "md5": "b5afa9848bcdfdce08252e8ccebd6ead"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.3-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7.3-sources.jar",
          "size": 66015,
          "sha512": "cb03e3c7f7a00dba9cddc5b8700897dea76446db972fb583834267bc9a91740b853719bd8c6ad1933e151632400884600ae11d0fbf0990551f96e131f75fa2ce",
          "sha256": "4d20dd31d32abe467ffc9c6ffdedb72c530bfb42f7093051774e10cc1773e56d",
          "sha1": "3fe8dc8ba92e29e1fa4c3f13fa0932fa8eff63eb",
          "md5": "0262a5df00fcc4ebb8a054eb4f8cf365"
        }
      ]
    }
  ]
}
