{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.aar",
          "url": "seattle_tv_sdk-1.3.2.7.aar",
          "size": 129872,
          "sha512": "ec17d7c1444e09e91b888e74d6539cd130501bf8ab34fbb189e7bae8f8172766da1fb7f614c297f825ee165588e39db62a4463923417cec54e1a971e942e9bb6",
          "sha256": "0d67116f8eaa4fe1351b48c93f80b1056485ccb1191cd68632a3842697719bbc",
          "sha1": "c7a99590d60bd9b65f2ef35b0642fb1051fba3cc",
          "md5": "b887fbe3a5e789f4d1cc9fbc1ea76c23"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.aar",
          "url": "seattle_tv_sdk-1.3.2.7.aar",
          "size": 129872,
          "sha512": "ec17d7c1444e09e91b888e74d6539cd130501bf8ab34fbb189e7bae8f8172766da1fb7f614c297f825ee165588e39db62a4463923417cec54e1a971e942e9bb6",
          "sha256": "0d67116f8eaa4fe1351b48c93f80b1056485ccb1191cd68632a3842697719bbc",
          "sha1": "c7a99590d60bd9b65f2ef35b0642fb1051fba3cc",
          "md5": "b887fbe3a5e789f4d1cc9fbc1ea76c23"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7-sources.jar",
          "size": 63539,
          "sha512": "7b79133ae8c8cfc0d91635555e5fc2a4a7bf272770cf0e153a04e45f80caf3d9bcfe66387218b7c6a2ed9490f6a9cae887a3bfd1447122b2c4154a1f986c7532",
          "sha256": "25cefebfd13bb730bc289262587b4fdd4eb9374c9c7ab57f6e54773a5c9268e9",
          "sha1": "2bec3b537384e461855b446f8832bc3b4e051048",
          "md5": "2de829f0dcf70113ac7a43c3cc912f6e"
        }
      ]
    }
  ]
}
