{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.1.aar",
          "url": "seattle_tv_sdk-1.3.2.7.1.aar",
          "size": 134372,
          "sha512": "c747bcfbc733675bc7c718524d15e2f4595302e4565c5f4993b9fc40b9ce80a1744149c25d589b677ce48f26e461b0017084f070847825196baaacfea1fbce00",
          "sha256": "e7ef2986265f3cc03688a77d3e9b3dfc5ac813bf5f0c6edc037e9b3b06441b0d",
          "sha1": "313e126094a249b12aeed43ac7a331106761d5e1",
          "md5": "d9053fc400ac3164d94ffee44e8f0e9d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.1.aar",
          "url": "seattle_tv_sdk-1.3.2.7.1.aar",
          "size": 134372,
          "sha512": "c747bcfbc733675bc7c718524d15e2f4595302e4565c5f4993b9fc40b9ce80a1744149c25d589b677ce48f26e461b0017084f070847825196baaacfea1fbce00",
          "sha256": "e7ef2986265f3cc03688a77d3e9b3dfc5ac813bf5f0c6edc037e9b3b06441b0d",
          "sha1": "313e126094a249b12aeed43ac7a331106761d5e1",
          "md5": "d9053fc400ac3164d94ffee44e8f0e9d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.1-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7.1-sources.jar",
          "size": 65455,
          "sha512": "a82034cfb91afcde10071af45370a1a871a3083c1644ac95ccf48e7dff0d02bca12c664a93d7afdb89a673244a35d7e2a939b226713b132d1451d764ed58c123",
          "sha256": "59b02f28ccab8321dd74a52201209813880cebd27f6cffdead9903cdc66d43ed",
          "sha1": "f11f6c90cb79ee228cdc81b2b82926c8344bcaaf",
          "md5": "b35b096088c46dbc1796ce7be5736551"
        }
      ]
    }
  ]
}
