{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.5.aar",
          "url": "seattle_tv_sdk-1.3.2.5.aar",
          "size": 147847,
          "sha512": "7b3c07de18c07962961896acaf02db30c99b190ad24062355e7cb0f0b50e7c121db8108e2a076fd1a3bfc1c90d33b0916874d09fd65ca3187efc15e4715f2c6f",
          "sha256": "e5f228dc56a245903f79b44b7cf0f2198367116311c38addfe1a7d7ce48f1216",
          "sha1": "7f045c52567119924cf7718ac304b06047ebc515",
          "md5": "0863c81a8ffb0c79f0948c051ff59385"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.5.aar",
          "url": "seattle_tv_sdk-1.3.2.5.aar",
          "size": 147847,
          "sha512": "7b3c07de18c07962961896acaf02db30c99b190ad24062355e7cb0f0b50e7c121db8108e2a076fd1a3bfc1c90d33b0916874d09fd65ca3187efc15e4715f2c6f",
          "sha256": "e5f228dc56a245903f79b44b7cf0f2198367116311c38addfe1a7d7ce48f1216",
          "sha1": "7f045c52567119924cf7718ac304b06047ebc515",
          "md5": "0863c81a8ffb0c79f0948c051ff59385"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.5-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.5-sources.jar",
          "size": 75401,
          "sha512": "1c8f04c93940be598666ecd494c645b44b0bd7c05015e40492f38e3ea2dd43931e5ba0c77832ee5a916acce9f6e391e92e4ba9d9e03c0195133d06b30274afe0",
          "sha256": "0f08a7fbdad3e588df5343e2e0b5488e2e638852ea92d1ae0574f1fc368ae5ff",
          "sha1": "c2c46c75b68e77a278f7f384998ea865c3b05ed9",
          "md5": "e336138aabb96af1b4225e0e16b31fb2"
        }
      ]
    }
  ]
}
