{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.2.aar",
          "url": "seattle_tv_sdk-1.3.2.2.aar",
          "size": 148392,
          "sha512": "3625df7992fdb498da6df38b60c10b685c2dbc39b110d12db0c933c18c51ba7d8e38ab9e4555c7c1290ec23860233b47e2da3dbe694d9871fb741632e35ef6ba",
          "sha256": "bdfad49ea10e9552c52df6cdaf3fda0b007cbdd913aced7583113d72cff87290",
          "sha1": "8e3f11bfc16fb8f0f7b66f0e1bb2b62df9077481",
          "md5": "13cd99cc5334fd964e7adde9c79c5fa3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-ijk",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cn.coolplay.player",
          "module": "clplayer-core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.2.aar",
          "url": "seattle_tv_sdk-1.3.2.2.aar",
          "size": 148392,
          "sha512": "3625df7992fdb498da6df38b60c10b685c2dbc39b110d12db0c933c18c51ba7d8e38ab9e4555c7c1290ec23860233b47e2da3dbe694d9871fb741632e35ef6ba",
          "sha256": "bdfad49ea10e9552c52df6cdaf3fda0b007cbdd913aced7583113d72cff87290",
          "sha1": "8e3f11bfc16fb8f0f7b66f0e1bb2b62df9077481",
          "md5": "13cd99cc5334fd964e7adde9c79c5fa3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.2-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.2-sources.jar",
          "size": 75113,
          "sha512": "f167faeb83a1a26619279785879893c370d49bad6add9c2d250d18fbe74f65147d06597bbd88a2b669db0f0c6149fea2ae9706d9a28e942ee907bdce74b0d1ad",
          "sha256": "79d42244ce680449627a89edaf9558816e8c1605f36b08a3b2f17a28ef089fa3",
          "sha1": "5f62108c8dd6d93852b533bebbd5953246c09e89",
          "md5": "81d31ce5815e2821e6c75decae9d7890"
        }
      ]
    }
  ]
}
