{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.2.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.5.aar",
          "url": "seattle_tv_sdk-1.3.2.7.5.aar",
          "size": 136192,
          "sha512": "1f924311e30a99a442b28eaa18ec2e855632bb2941aa9a00a54c47e66ee11f552799076e6fc9bc8068c0f943318dcfece258f292a7b468a0fcff62ed2fbc6e5b",
          "sha256": "84161b4337a7aad2716375e9f596603048738f8b6fb9f4ba5671957f0ebfe094",
          "sha1": "0e617c1099076c653d2a5d6cba0c4f61f6ead59f",
          "md5": "8b1fd893c8c430060ca5504df67b633a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.5.aar",
          "url": "seattle_tv_sdk-1.3.2.7.5.aar",
          "size": 136192,
          "sha512": "1f924311e30a99a442b28eaa18ec2e855632bb2941aa9a00a54c47e66ee11f552799076e6fc9bc8068c0f943318dcfece258f292a7b468a0fcff62ed2fbc6e5b",
          "sha256": "84161b4337a7aad2716375e9f596603048738f8b6fb9f4ba5671957f0ebfe094",
          "sha1": "0e617c1099076c653d2a5d6cba0c4f61f6ead59f",
          "md5": "8b1fd893c8c430060ca5504df67b633a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.2.7.5-sources.jar",
          "url": "seattle_tv_sdk-1.3.2.7.5-sources.jar",
          "size": 66737,
          "sha512": "46186b80d6c9372e22fac1fe9f89ff19917d1beda1a40ac648771796fa92b3c5cb354046437f256987e4ec7529132d5fe3acf603c1936029ee46bd4c2ebced49",
          "sha256": "96afd88880dadd147333c3d77c47d23a14541e238394e173ee8a3d9934b11a77",
          "sha1": "46119a073e785f57684375774f782411b49bb6a0",
          "md5": "ca5640ebd657c027df108bb3f14a7b3d"
        }
      ]
    }
  ]
}
