{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk",
    "version": "1.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-arm64",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "com.zeasn.ad.connector",
          "module": "connector",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.zeasn",
          "module": "ad_vast_sdk",
          "version": {
            "requires": "8.0.0.16"
          }
        },
        {
          "group": "com.zeasn",
          "module": "tou_sdk",
          "version": {
            "requires": "3.1.0.64"
          },
          "excludes": [
            {
              "group": "*",
              "module": "leanback"
            }
          ]
        },
        {
          "group": "com.zeasn.common",
          "module": "common",
          "version": {
            "requires": "1.1.77"
          }
        },
        {
          "group": "com.zeasn.analytics",
          "module": "core",
          "version": {
            "requires": "1.1.77"
          }
        },
        {
          "group": "com.zeasn",
          "module": "dp-api",
          "version": {
            "requires": "0.2.25"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-ima",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-cronet",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.0.2.aar",
          "url": "seattle_tv_sdk-1.3.0.2.aar",
          "size": 134338,
          "sha512": "b6c0975e2b6ef101ec82a8e364d13f9ce4a8c2b27c69195d7090d9363764d717d5543bc54961cb16b361bad3f0a18c9c0339dbb4f09d195c113e4ca994e2cca8",
          "sha256": "071ed4f124cf13f526097214845b6db7f86ed4fefb72c63495734556fd058318",
          "sha1": "73eacb005698d1e070d2670e8981a4b9105a8454",
          "md5": "0600e404a2493b04823c5aa412a7704e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "xyz.doikki.android.dkplayer",
          "module": "videocache",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-java",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-armv7a",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent.iot.thirdparty.android",
          "module": "ijkplayer-arm64",
          "version": {
            "requires": "2.0.15"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "com.zeasn.ad.connector",
          "module": "connector",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.zeasn",
          "module": "ad_vast_sdk",
          "version": {
            "requires": "8.0.0.16"
          }
        },
        {
          "group": "com.zeasn",
          "module": "tou_sdk",
          "version": {
            "requires": "3.1.0.64"
          },
          "excludes": [
            {
              "group": "*",
              "module": "leanback"
            }
          ]
        },
        {
          "group": "com.zeasn.common",
          "module": "common",
          "version": {
            "requires": "1.1.77"
          }
        },
        {
          "group": "com.zeasn.analytics",
          "module": "core",
          "version": {
            "requires": "1.1.77"
          }
        },
        {
          "group": "com.zeasn",
          "module": "dp-api",
          "version": {
            "requires": "0.2.25"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-ima",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-cronet",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.0.2.aar",
          "url": "seattle_tv_sdk-1.3.0.2.aar",
          "size": 134338,
          "sha512": "b6c0975e2b6ef101ec82a8e364d13f9ce4a8c2b27c69195d7090d9363764d717d5543bc54961cb16b361bad3f0a18c9c0339dbb4f09d195c113e4ca994e2cca8",
          "sha256": "071ed4f124cf13f526097214845b6db7f86ed4fefb72c63495734556fd058318",
          "sha1": "73eacb005698d1e070d2670e8981a4b9105a8454",
          "md5": "0600e404a2493b04823c5aa412a7704e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk-1.3.0.2-sources.jar",
          "url": "seattle_tv_sdk-1.3.0.2-sources.jar",
          "size": 70939,
          "sha512": "6f609b55c598c44fcc116ec1c992bc22c521f1f7bd6a7b35d9dc65638fbfbb3aa67c37370e90c4573214ef405b12a2af7cb46fc96f3d974d45aa1b831d8b5dfd",
          "sha256": "a348313ac4eaa844ce125a483d7310aaa3af8735c086e5f1aa8cb816145ec2b5",
          "sha1": "4ac5397a2b4fa01ba6942ee0071d4d431ada8ba8",
          "md5": "db5c5b80e13d9f83598100f41fa55473"
        }
      ]
    }
  ]
}
