{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.coolplay",
    "module": "seattle_tv_sdk_airmobi",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi-1.0.1.aar",
          "url": "seattle_tv_sdk_airmobi-1.0.1.aar",
          "size": 6765,
          "sha512": "d562e60a0ea78af6dd1fbfaef07d1e4c18ab88ab47376ac27f419fec19f47fefca73060f5c9e3ee60d3ac1957d11f18e47297ada60986961179c9235c2297adf",
          "sha256": "941e8c20f04a7aef16a3c793b39cb9990e49ebf0a8e6198ad92b1e13a27c3e0d",
          "sha1": "726fff196f8ec36250d119de718d1beca126df04",
          "md5": "82f9841a04ddb779d782c8ad3b37b443"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi-1.0.1.aar",
          "url": "seattle_tv_sdk_airmobi-1.0.1.aar",
          "size": 6765,
          "sha512": "d562e60a0ea78af6dd1fbfaef07d1e4c18ab88ab47376ac27f419fec19f47fefca73060f5c9e3ee60d3ac1957d11f18e47297ada60986961179c9235c2297adf",
          "sha256": "941e8c20f04a7aef16a3c793b39cb9990e49ebf0a8e6198ad92b1e13a27c3e0d",
          "sha1": "726fff196f8ec36250d119de718d1beca126df04",
          "md5": "82f9841a04ddb779d782c8ad3b37b443"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "seattle_tv_sdk_airmobi-1.0.1-sources.jar",
          "url": "seattle_tv_sdk_airmobi-1.0.1-sources.jar",
          "size": 4393,
          "sha512": "17cfeeec91ed1360c5f99d0bead8c3e14480c2625e4e9c7d813415f936fdd3be8d2adbce6f7134e2e9da037b7b0263f57b5ff678017f9a5c063e26061520816f",
          "sha256": "71ed5e4e45a922f036c96854933a1035af45c26319cebb5139f494feed002839",
          "sha1": "264b5cc8e63b2af4d79419fa7757101f159393ec",
          "md5": "2b9cd6fe84260ade8bc3965f14cdbef1"
        }
      ]
    }
  ]
}
